In [2]:
import pandas as pd
import gmaps
import gmaps.datasets
from Config import gkey

import warnings
warnings.filterwarnings('ignore')

In [3]:
file = "Resources/Chicago_Traffic_Tracker_-_Congestion_Estimates_by_Regions.csv"
zones_df = pd.read_csv(file)
zones_df.head()

,REGION,REGION_ID,WEST,EAST,SOUTH,NORTH,DESCRIPTION,CURRENT_SPEED,LAST_UPDATED
0,Rogers Park - West Ridge,1,-87.709645,-87.654561,41.997946,42.026444,North of Devon. Kedzie to Lake Shore,21.82,2019-03-26 20:01:37.0
1,Austin,9,-87.775947,-87.747456,41.866129,41.909269,Roosevelt to North Ave. Austin to Cicero,24.55,2019-03-26 20:01:38.0
2,Near North,12,-87.647208,-87.623080,41.888860,41.911401,Wacker to North. Halsted to Michigan,20.45,2019-03-26 20:01:38.0
3,Midway-Garfield Rdg-Clearing,17,-87.802188,-87.747456,41.764066,41.822792,71st to Pershing. Halem to Cicero,30.68,2019-03-26 20:01:38.0
4,West Town-Near West,11,-87.691617,-87.647208,41.866129,41.910561,Roosevelt to North. Rockwell to Halsted,22.50,2019-03-26 20:01:38.0

In [4]:
zones_df[[" REGION_ID"," WEST", " EAST", " SOUTH", " NORTH"]]

     REGION_ID       WEST       EAST      SOUTH      NORTH
0            1 -87.709645 -87.654561  41.997946  42.026444
1            9 -87.775947 -87.747456  41.866129  41.909269
2           12 -87.647208 -87.623080  41.888860  41.911401
3           17 -87.802188 -87.747456  41.764066  41.822792
4           11 -87.691617 -87.647208  41.866129  41.910561
5            8 -87.674590 -87.619112  41.910561  41.960669
6           21 -87.606334 -87.566260  41.764066  41.822792
7           29 -87.623080 -87.595378  41.866129  41.911401
8           22 -87.747456 -87.672980  41.728472  41.764066
9            2 -87.846210 -87.747456  41.960669  42.019100
10           4 -87.674590 -87.646438  41.960669  41.997946
11           7 -87.747456 -87.674590  41.909269  41.931841
12          19 -87.683730 -87.636322  41.764066  41.822792
13          28 -87.662508 -87.524436  41.644139  41.677477
14           6 -87.747456 -87.674590  41.931841  41.960669
15          24 -87.606334 -87.526388  41.728472  41.764066
16          10 -87.747456 -87.691617  41.866129  41.909269
17          26 -87.662508 -87.584845  41.677477  41.728472
18          27 -87.584845 -87.524436  41.677477  41.728472
19          16 -87.636322 -87.597952  41.822792  41.866129
20          13 -87.647208 -87.623080  41.866129  41.888860
21          25 -87.747456 -87.662508  41.677477  41.728472
22           5 -87.846210 -87.747456  41.909269  41.960669
23           3 -87.747456 -87.674590  41.960669  41.997946
24          15 -87.685372 -87.636322  41.822792  41.866129
25          20 -87.636322 -87.606334  41.764066  41.822792
26          23 -87.672980 -87.606334  41.728472  41.764066
27          18 -87.747456 -87.683730  41.764066  41.822792
28          14 -87.747456 -87.685372  41.822792  41.866129

In [20]:
zones_df["Midpoint 1"] = ((zones_df[" WEST"] + zones_df[" EAST"])/2)
zones_df["Midpoint 2"] = ((zones_df[" SOUTH"] + zones_df[" NORTH"])/2)
zones_df.head()

,REGION,REGION_ID,WEST,EAST,SOUTH,NORTH,DESCRIPTION,CURRENT_SPEED,LAST_UPDATED,Midpoint 1,Midpoint 2
0,Rogers Park - West Ridge,1,-87.709645,-87.654561,41.997946,42.026444,North of Devon. Kedzie to Lake Shore,21.82,2019-03-26 20:01:37.0,-87.682103,42.012195
1,Austin,9,-87.775947,-87.747456,41.866129,41.909269,Roosevelt to North Ave. Austin to Cicero,24.55,2019-03-26 20:01:38.0,-87.761702,41.887699
2,Near North,12,-87.647208,-87.623080,41.888860,41.911401,Wacker to North. Halsted to Michigan,20.45,2019-03-26 20:01:38.0,-87.635144,41.900131
3,Midway-Garfield Rdg-Clearing,17,-87.802188,-87.747456,41.764066,41.822792,71st to Pershing. Halem to Cicero,30.68,2019-03-26 20:01:38.0,-87.774822,41.793429
4,West Town-Near West,11,-87.691617,-87.647208,41.866129,41.910561,Roosevelt to North. Rockwell to Halsted,22.50,2019-03-26 20:01:38.0,-87.669412,41.888345

In [22]:
zones_df[["Midpoint 1", "Midpoint 2"]]

    Midpoint 1  Midpoint 2
0   -87.682103   42.012195
1   -87.761702   41.887699
2   -87.635144   41.900131
3   -87.774822   41.793429
4   -87.669412   41.888345
5   -87.646851   41.935615
6   -87.586297   41.793429
7   -87.609229   41.888765
8   -87.710218   41.746269
9   -87.796833   41.989884
10  -87.660514   41.979308
11  -87.711023   41.920555
12  -87.660026   41.793429
13  -87.593472   41.660808
14  -87.711023   41.946255
15  -87.566361   41.746269
16  -87.719537   41.887699
17  -87.623677   41.702974
18  -87.554641   41.702974
19  -87.617137   41.844460
20  -87.635144   41.877494
21  -87.704982   41.702974
22  -87.796833   41.934969
23  -87.711023   41.979308
24  -87.660847   41.844460
25  -87.621328   41.793429
26  -87.639657   41.746269
27  -87.715593   41.793429
28  -87.716414   41.844460

In [6]:
gmaps.configure(api_key = gkey)
gmaps.figure()

Figure(layout=FigureLayout(height='420px'))

In [7]:
#Create a list of coordinates for our figure
SW = []
NW = []
SE = []
NE = []

for index, row in zones_df.iterrows():
    temp = []
    temp.append(row[" NORTH"])
    temp.append(row[" EAST"])
    NE.append(temp)

for index,row in zones_df.iterrows():
    temp = []
    temp.append(row[" NORTH"])
    temp.append(row[" WEST"])
    NW.append(temp)
    
for index,row in zones_df.iterrows():
    temp = []
    temp.append(row[" SOUTH"])
    temp.append(row[" EAST"])
    SE.append(temp)
    
for index,row in zones_df.iterrows():
    temp = []
    temp.append(row[" SOUTH"])
    temp.append(row[" WEST"])
    SW.append(temp)    

print(SW)

[[41.997946, -87.709645], [41.866129, -87.775947], [41.88886, -87.64720799999999], [41.764066, -87.802188], [41.866129, -87.69161700000001], [41.910561, -87.67459000000001], [41.764066, -87.60633399999999], [41.866129, -87.62308], [41.728472, -87.747456], [41.960669, -87.84621], [41.960669, -87.67459000000001], [41.909269, -87.747456], [41.764066, -87.68373000000001], [41.644139, -87.662508], [41.931841, -87.747456], [41.728472, -87.60633399999999], [41.866129, -87.747456], [41.677477, -87.662508], [41.677477, -87.584845], [41.822792, -87.63632199999999], [41.866129, -87.64720799999999], [41.677477, -87.747456], [41.909269, -87.84621], [41.960669, -87.747456], [41.822792, -87.685372], [41.764066, -87.63632199999999], [41.728472, -87.67298000000001], [41.764066, -87.747456], [41.822792, -87.747456]]

In [8]:

north = zones_df[" NORTH"]
south = zones_df[" SOUTH"]
west = zones_df[" WEST"]
east = zones_df[" EAST"]
    
    
print(north)

0     42.026444
1     41.909269
2     41.911401
3     41.822792
4     41.910561
5     41.960669
6     41.822792
7     41.911401
8     41.764066
9     42.019100
10    41.997946
11    41.931841
12    41.822792
13    41.677477
14    41.960669
15    41.764066
16    41.909269
17    41.728472
18    41.728472
19    41.866129
20    41.888860
21    41.728472
22    41.960669
23    41.997946
24    41.866129
25    41.822792
26    41.764066
27    41.822792
28    41.866129
Name:  NORTH, dtype: float64

In [9]:
#Make coordinates into a distinct zone list
coords = []

for x in range(29):
    temp = []
    temp.append(NE[x])
    temp.append(SE[x])
    temp.append(SW[x])
    temp.append(NW[x])
    coords.append(temp)
    
print(coords[0])

[[42.026444, -87.654561], [41.997946, -87.654561], [41.997946, -87.709645], [42.026444, -87.709645]]

In [32]:
#Make the map
fig = gmaps.figure(center=(41.835966, -87.825), zoom_level=11)
# drawing = gmaps.drawing_layer(features = 
#                              gmaps.Polygon(north[0], west[0], north[0], east[0], south[0], west[0], south[0], east[0]))

for x in range(29):
    region_layer = gmaps.drawing_layer(features = [
        gmaps.Polygon(
            coords[x],
            stroke_color='blue', stroke_weight=1, fill_color='blue', fill_opacity=.2
        )
    ])
    fig.add_layer(region_layer)
#fig = gmaps.figure()
#zoom_level = 11

locations = [
    (42.012195, -87.682103),
    (41.887699, -87.681702),
    (41.900131, -87.635144),
    (41.793429, -87.774822),
    (41.888345, -87.669412),
    (41.935615, -87.646851),
    (41.793429, -87.586297),
    (41.888765, -87.609229),
    (41.746269, -87.710218),
    (41.989884, -87.796833),
    (41.979308, -87.660514),
    (41.920555, -87.711023),
    (41.793429, -87.660026),
    (41.660808, -87.593472),
    (41.946255, -87.711023),
    (41.746269, -87.566361),
    (41.887699, -87.719537),
    (41.702974, -87.623677),
    (41.702974, -87.554641),
    (41.844460, -87.617137),
    (41.877494, -87.635144),
    (41.702974, -87.704982),
    (41.934969, -87.796833),
    (41.979308, -87.711023),
    (41.844460, -87.660847),
    (41.793429, -87.621328),
    (41.746269, -87.639657),
    (41.793429, -87.715593),
    (41.844460, -87.716414),
    
]

marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)
fig

    
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
rl_cams = pd.read_csv("Resources/Red_Light_Camera_Locations.csv", low_memory=False)
rl_location = rl_cams.loc[:,"LATITUDE":"LONGITUDE"]
rl_location["LATITUDE"].dropna(how='any', inplace=True)
rl_location["LONGITUDE"].dropna(how='any', inplace=True)
rl_location.rename(columns={"LATITUDE": "Lat", "LONGITUDE":"Lng"}, inplace=True)
rl_intersection = rl_cams.loc[:,"INTERSECTION"]

In [12]:
speed_cams = pd.read_csv("Resources/Speed_Camera_locations.csv", low_memory=False)
speed_location = speed_cams.loc[:,"LATITUDE":"LONGITUDE"]
speed_location["LATITUDE"].dropna(how='any', inplace=True)
speed_location["LONGITUDE"].dropna(how='any', inplace=True)
speed_location.rename(columns={"LATITUDE": "Lat", "LONGITUDE":"Lng"}, inplace=True)
speed_address = speed_cams.loc[:,"ADDRESS"]

In [13]:
rl_intersection_layer = gmaps.symbol_layer(
    rl_location, fill_color='rgba(150, 0, 0, 0.4)',
    stroke_color='rgba(150, 0, 0, 0.2)', scale=2,
    info_box_content=[f"Location: {intersection}" for intersection in rl_intersection]
)

speed_address_layer = gmaps.symbol_layer(
    speed_location, fill_color='rgba(0, 150, 0, 0.5)',
    stroke_color='rgba(0, 150, 0, 0.3)', scale=2,
    info_box_content=[f"Location: {address}" for address in speed_address]
)

#Make the map
fig = gmaps.figure(center=(41.835966, -87.825), zoom_level=11)

fig.add_layer(rl_intersection_layer)
fig.add_layer(speed_address_layer)

for x in range(29):
    region_layer = gmaps.drawing_layer(features = [
        gmaps.Polygon(
            coords[x],
            stroke_color='blue', stroke_weight=1, fill_color='blue', fill_opacity=.05
        )
    ])
    fig.add_layer(region_layer)


fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
fig = gmaps.figure()
zoom_level = 11

locations = [
    (42.012195, -87.682103),
    (41.887699, -87.681702),
    (41.900131, -87.635144),
    (41.793429, -87.774822),
    (41.888345, -87.669412),
    (41.935615, -87.646851),
    (41.793429, -87.586297),
    (41.888765, -87.609229),
    (41.746269, -87.710218),
    (41.989884, -87.796833),
    (41.979308, -87.660514),
    (41.920555, -87.711023),
    (41.793429, -87.660026),
    (41.660808, -87.593472),
    (41.946255, -87.711023),
    (41.746269, -87.566361),
    (41.887699, -87.719537),
    (41.702974, -87.623677),
    (41.702974, -87.554641),
    (41.844460, -87.617137),
    (41.877494, -87.635144),
    (41.702974, -87.704982),
    (41.934969, -87.796833),
    (41.979308, -87.711023),
    (41.844460, -87.660847),
    (41.793429, -87.621328),
    (41.746269, -87.639657),
    (41.793429, -87.715593),
    (41.844460, -87.716414),
    
]

marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))